/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kenneth
 */
public class traductor extends javax.swing.JFrame {

    /**
     * Creates new form traductor
     */
    
    private File archivoActual;
    private boolean archivoGuardado = false;  

    public traductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_procesar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        longitud_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ptotal_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        primer_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ulti_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        centro_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        primerapalabra_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        centralapalabra_txt = new javax.swing.JTextField();
        ulimapalabra_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reppU_txt = new javax.swing.JTextField();
        reppA_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        par_txt = new javax.swing.JTextField();
        reppE_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        impar_txt = new javax.swing.JTextField();
        reppI_txt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        reppO_txt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taduc_txt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pantallaentrada_txt = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrir_menu = new javax.swing.JMenuItem();
        guardar_menu = new javax.swing.JMenuItem();
        guardarcomo_menu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        peg_menu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        busc_menu = new javax.swing.JMenuItem();
        reem_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Manejo de cadenas");

        jLabel2.setText("Ingresa un texto o abra un archivo ");
        jLabel2.setOpaque(true);

        btn_procesar.setText("Procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        jLabel3.setText("Longitud del texto");

        jLabel4.setText("Palabras en Total ");

        jLabel5.setText("Primera letra del texto ");

        jLabel6.setText("Última letra del texto ");

        jLabel7.setText("Letra del Centro ");

        jLabel8.setText("Primera palabra ");

        jLabel9.setText("Palabra central ");

        jLabel10.setText("Última palabra ");

        jLabel11.setText("Repeticiones de \"U\", \"u\" o \"ú\" ");

        jLabel12.setText("Repeticiones de \"A\", \"a\" o \"á\" ");

        jLabel13.setText("Palabras con cantidad de caracteres par ");

        jLabel14.setText("Repeticiones de \"E\", \"e\" o \"é\" ");

        jLabel15.setText("Palabras con cantidad de caracteres impar ");

        jLabel16.setText("Repeticiones de \"I\", \"i\" o \"í\" ");

        jLabel17.setText("Repeticiones de \"O\", \"o\" o \"ó\" ");

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel18.setText("Traducción");
        jLabel18.setOpaque(true);

        taduc_txt.setColumns(20);
        taduc_txt.setRows(5);
        jScrollPane1.setViewportView(taduc_txt);

        pantallaentrada_txt.setColumns(20);
        pantallaentrada_txt.setRows(5);
        jScrollPane2.setViewportView(pantallaentrada_txt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(38, 38, 38)
                                        .addComponent(ptotal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(38, 38, 38)
                                        .addComponent(longitud_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(38, 38, 38)
                                        .addComponent(primer_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(38, 38, 38)
                                        .addComponent(primerapalabra_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(38, 38, 38)
                                        .addComponent(centro_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(38, 38, 38)
                                        .addComponent(centralapalabra_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(38, 38, 38)
                                        .addComponent(ulimapalabra_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(38, 38, 38)
                                        .addComponent(ulti_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(38, 38, 38)
                                        .addComponent(reppE_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(38, 38, 38)
                                        .addComponent(reppA_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(38, 38, 38)
                                        .addComponent(reppI_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(38, 38, 38)
                                        .addComponent(reppO_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(38, 38, 38)
                                        .addComponent(par_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(38, 38, 38)
                                        .addComponent(reppU_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(38, 38, 38)
                                        .addComponent(impar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_procesar)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(350, 350, 350))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_procesar)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(longitud_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ptotal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(primer_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ulti_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(centro_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(primerapalabra_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(centralapalabra_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ulimapalabra_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(reppA_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(reppE_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(reppI_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(reppO_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(reppU_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(par_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(impar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jMenu1.setText("Archivo");

        abrir_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        abrir_menu.setText("Abrir");
        abrir_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrir_menuActionPerformed(evt);
            }
        });
        jMenu1.add(abrir_menu);

        guardar_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        guardar_menu.setText("Guardar");
        guardar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_menuActionPerformed(evt);
            }
        });
        jMenu1.add(guardar_menu);

        guardarcomo_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        guardarcomo_menu.setText("Guardar como");
        guardarcomo_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarcomo_menuActionPerformed(evt);
            }
        });
        jMenu1.add(guardarcomo_menu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        peg_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        peg_menu.setText("Copiar");
        peg_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peg_menuActionPerformed(evt);
            }
        });
        jMenu2.add(peg_menu);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Cortar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Pegar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        busc_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        busc_menu.setText("Buscar");
        busc_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busc_menuActionPerformed(evt);
            }
        });
        jMenu2.add(busc_menu);

        reem_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        reem_menu.setText("Reemplazar");
        reem_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reem_menuActionPerformed(evt);
            }
        });
        jMenu2.add(reem_menu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirArchivo() {
    JFileChooser fileChooser = new JFileChooser();
    int seleccion = fileChooser.showOpenDialog(this);

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        archivoActual = fileChooser.getSelectedFile();
        archivoGuardado = true; 
        try {
            // Leer el archivo
            BufferedReader reader = new BufferedReader(new FileReader(archivoActual));
            StringBuilder texto = new StringBuilder();
            String linea;
            while ((linea = reader.readLine()) != null) {
                texto.append(linea).append("\n");
            }
            reader.close();

            // Mostrar el contenido en el área de texto original
            pantallaentrada_txt.setText(texto.toString());

            // Traducir el texto y mostrarlo en el área correspondiente
            String textoTraducido = traducirClaveMurcielago(texto.toString());
            taduc_txt.setText(textoTraducido);

            // Procesar estadísticas del texto original
            procesarTexto(texto.toString());

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo: " + ex.getMessage());
        }
    }
}
private void guardarArchivo(File archivo) {
   try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo))) {
        writer.write(pantallaentrada_txt.getText());  // Guardar el texto original
        JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente.");
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage());
    }
}

private void guardarComo() {
       JFileChooser fileChooser = new JFileChooser();
    
    // Filtro para archivos .txt
    FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt");
    fileChooser.setFileFilter(filtro);

    // Mostrar diálogo de guardar como
    int seleccion = fileChooser.showSaveDialog(this);

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        File archivo = fileChooser.getSelectedFile();
        
        // Asegurarse de que el archivo tenga la extensión .txt
        if (!archivo.getName().endsWith(".txt")) {
            archivo = new File(archivo.getAbsolutePath() + ".txt");
        }
        
        archivoActual = archivo;
        guardarArchivo(archivo);
    }
}
    
    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
 // Obtener el texto ingresado por el usuario
    String textoOriginal = pantallaentrada_txt.getText();

    // Procesar las estadísticas ANTES de traducir el texto
    procesarTexto(textoOriginal);  // Llamada al método que realiza los cálculos y actualiza los campos

    // Convertir el texto utilizando la clave Murciélago
    String textoTraducido = traducirClaveMurcielago(textoOriginal);

    // Mostrar el texto traducido en el área de texto
    taduc_txt.setText(textoTraducido);

    }//GEN-LAST:event_btn_procesarActionPerformed

    private void abrir_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrir_menuActionPerformed
 abrirArchivo();        // TODO add your handling code here:
    }//GEN-LAST:event_abrir_menuActionPerformed

    private void guardar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_menuActionPerformed
 if (archivoActual != null) {
        guardarArchivo(archivoActual);  // Sobrescribe el archivo existente
    } else {
        guardarComo();  // Si no, actúa como "Guardar como"
    }      // TODO add your handling code here:
    }//GEN-LAST:event_guardar_menuActionPerformed

    private void guardarcomo_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarcomo_menuActionPerformed
guardarComo();        // TODO add your handling code here:
    }//GEN-LAST:event_guardarcomo_menuActionPerformed

    private void peg_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peg_menuActionPerformed
     pantallaentrada_txt.copy();
    }//GEN-LAST:event_peg_menuActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      pantallaentrada_txt.paste();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void busc_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busc_menuActionPerformed
 String buscarTexto = JOptionPane.showInputDialog(this, "Buscar:");
    if (buscarTexto != null && !buscarTexto.isEmpty()) {
        String contenido = pantallaentrada_txt.getText();
        int startIndex = contenido.indexOf(buscarTexto);
        if (startIndex != -1) {
            pantallaentrada_txt.setCaretPosition(startIndex);
            pantallaentrada_txt.select(startIndex, startIndex + buscarTexto.length());
        } else {
            JOptionPane.showMessageDialog(this, "Texto no encontrado.");
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_busc_menuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     pantallaentrada_txt.cut(); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void reem_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reem_menuActionPerformed
String buscarTexto = JOptionPane.showInputDialog(this, "Buscar:");
    if (buscarTexto != null && !buscarTexto.isEmpty()) {
        String reemplazarTexto = JOptionPane.showInputDialog(this, "Reemplazar por:");
        if (reemplazarTexto != null) {
            String contenido = pantallaentrada_txt.getText();
            String nuevoContenido = contenido.replaceAll(Pattern.quote(buscarTexto), Matcher.quoteReplacement(reemplazarTexto));
            pantallaentrada_txt.setText(nuevoContenido);
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_reem_menuActionPerformed



private int contarCaracteres(String texto, char... caracteres) {
    int contador = 0;
    texto = texto.toLowerCase(); // Convertimos el texto a minúsculas para facilitar la comparación

    for (char c : texto.toCharArray()) {  // Iteramos sobre cada carácter del texto
        for (char caracter : caracteres) {
            if (c == caracter) {
                contador++;
            }
        }
    }

    return contador;
}


private void procesarTexto(String texto) {
    // Longitud del texto
    longitud_txt.setText(String.valueOf(texto.length()));

    // Palabras en total
    String[] palabras = texto.split("\\s+");
    ptotal_txt.setText(String.valueOf(palabras.length));

    // Primera letra del texto
    if (texto.length() > 0) {
        primer_txt.setText(String.valueOf(texto.charAt(0)));
    } else {
        primer_txt.setText("");
    }

    // Última letra del texto
    if (texto.length() > 0) {
        ulti_txt.setText(String.valueOf(texto.charAt(texto.length() - 1)));
    } else {
        ulti_txt.setText("");
    }

    // Letra del centro
    if (texto.length() > 0) {
        centro_txt.setText(String.valueOf(texto.charAt(texto.length() / 2)));
    } else {
        centro_txt.setText("");
    }

    // Primera palabra
    if (palabras.length > 0) {
        primerapalabra_txt.setText(palabras[0]);
    } else {
        primerapalabra_txt.setText("");
    }

    // Palabra central
    if (palabras.length > 0) {
        centralapalabra_txt.setText(palabras[palabras.length / 2]);
    } else {
        centralapalabra_txt.setText("");
    }

    // Última palabra
    if (palabras.length > 0) {
        ulimapalabra_txt.setText(palabras[palabras.length - 1]);
    } else {
        ulimapalabra_txt.setText("");
    }

    // Contar repeticiones de vocales en el texto completo
    reppA_txt.setText(String.valueOf(contarCaracteres(texto, 'a', 'á')));
    reppE_txt.setText(String.valueOf(contarCaracteres(texto, 'e', 'é')));
    reppI_txt.setText(String.valueOf(contarCaracteres(texto, 'i', 'í')));
    reppO_txt.setText(String.valueOf(contarCaracteres(texto, 'o', 'ó')));
    reppU_txt.setText(String.valueOf(contarCaracteres(texto, 'u', 'ú', 'ü')));



    // Palabras con cantidad de caracteres par e impar
    int pares = 0, impares = 0;
    for (String palabra : palabras) {
        if (palabra.length() % 2 == 0) {
            pares++;
        } else {
            impares++;
        }
    }
    par_txt.setText(String.valueOf(pares));
    impar_txt.setText(String.valueOf(impares));
}











// Método para traducir una cadena a la clave Murciélago
private String traducirClaveMurcielago(String texto) {
    // Definir la clave Murciélago
    String claveOriginal = "murcielago";
    String claveNueva = "0123456789";

    // Convertir el texto
    StringBuilder textoTraducido = new StringBuilder();

    for (char c : texto.toLowerCase().toCharArray()) {
        int indice = claveOriginal.indexOf(c);
        if (indice != -1) {
            // Reemplazar por el número correspondiente en la clave Murciélago
            textoTraducido.append(claveNueva.charAt(indice));
        } else {
            // Si el carácter no está en la clave, se mantiene igual
            textoTraducido.append(c);
        }
    }

    return textoTraducido.toString();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new traductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir_menu;
    private javax.swing.JButton btn_procesar;
    private javax.swing.JMenuItem busc_menu;
    private javax.swing.JTextField centralapalabra_txt;
    private javax.swing.JTextField centro_txt;
    private javax.swing.JMenuItem guardar_menu;
    private javax.swing.JMenuItem guardarcomo_menu;
    private javax.swing.JTextField impar_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField longitud_txt;
    private javax.swing.JTextArea pantallaentrada_txt;
    private javax.swing.JTextField par_txt;
    private javax.swing.JMenuItem peg_menu;
    private javax.swing.JTextField primer_txt;
    private javax.swing.JTextField primerapalabra_txt;
    private javax.swing.JTextField ptotal_txt;
    private javax.swing.JMenuItem reem_menu;
    private javax.swing.JTextField reppA_txt;
    private javax.swing.JTextField reppE_txt;
    private javax.swing.JTextField reppI_txt;
    private javax.swing.JTextField reppO_txt;
    private javax.swing.JTextField reppU_txt;
    private javax.swing.JTextArea taduc_txt;
    private javax.swing.JTextField ulimapalabra_txt;
    private javax.swing.JTextField ulti_txt;
    // End of variables declaration//GEN-END:variables
}
